Create mocha.opts
Tests would not run properly due to timeout. Adding this file resolved the issue for the student who encountered the issue. 
Failing test:
1) arrays "before all" hook:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.